# -*- coding: utf-8 -*-
"""ELEVATE TASK 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdVsnoKsuQlh0Dk46NL8NcgHvVCO7Bkp
"""

import zipfile
import os
from PIL import Image

source_zip = "/content/TASK 7 IMAGES.zip"
source_folder_unzipped = "/content/TASK 7 IMAGES"  # Changed to a directory
destination_folder = "/content/TASK 7 RESIZED IMAGES" # Changed to a directory

# Create destination folder if it doesn't exist
if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

# Create unzipped folder if it doesn't exist
if not os.path.exists(source_folder_unzipped):
    os.makedirs(source_folder_unzipped)

with zipfile.ZipFile(source_zip, 'r') as zip_ref:
    zip_ref.extractall(source_folder_unzipped)

new_size = (800, 600)

for filename in os.listdir(source_folder_unzipped):
    if filename.lower().endswith((".png", ".jpg", ".jpeg")):
        img_path = os.path.join(source_folder_unzipped, filename)

        try:
            with Image.open(img_path) as img:
                resized_img = img.resize(new_size)
                save_path = os.path.join(destination_folder, filename) # Save to destination folder
                resized_img.save(save_path)
            print(f"{filename} resized and saved successfully.")
        except Exception as e:
            print(f"Error processing {filename}: {e}")

print("All images have been resized!")